### Note: DO NOT use quantized model or quantization_bit when merging lora adapters

### model
model_name_or_path: Qwen/Qwen3-8B
adapter_name_or_path: saves/lora_2
template: qwen
trust_remote_code: true

### export
export_dir: output/qwen_lora_2
export_size: 5
export_device: cpu  # choices: [cpu, auto]
export_legacy_format: false
